language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t manojjonam/react-app-tst -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true manojjonam/react-app-tst npm test

after_success:
  - docker build -t manojjonam/multi-client ./client
  - docker build -t manojjonam/multi-ngnix ./ngnix
  - docker build -t manojjonam/multi-server ./server
  - docker build -t manojjonam/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push manojjonam/multi-client
  - docker push manojjonam/multi-ngnix
  - docker push manojjonam/multi-server
  - docker push manojjonam/multi-worker